### ISSUE TITLE
Margin in DSA Practice page and missing go back button

### ISSUE THREAD

**Issue by alkatrivedi** [Algo-Phantoms/Algo-Phantoms-Frontend#231] opened 2021-03-23 05:02 UTC
## **Describe the bug**

- There is a margin on the right side of the practice problem sheet on the DSA problem page. Also, there is no navbar or any go back button on this page which leaves a bad impact if a user wants to go back on any other page of the website.

## **Possible solution**

- The DSA problem sheet should not have any margin on the left or right side so I am thinking of removing that margin. Also, there is no go back button on this page so I am thinking to add a navbar on top of the page(we may add a go back button on the bottom of the page also but I guess a navbar would be good to add).

## **Screenshots**
![Capture](https://user-images.githubusercontent.com/58396306/112095581-c205ac00-8bc2-11eb-8d52-4a13c67f098a.PNG)

The issue is this margin on the right side of the sheet. Or no any navbar or go back button.

I am a GSSoC'21 participant and I would like to work on this issue. May I work on it under GSSoC'21?

**Comment by harikesh409** [comment] 2021-03-23 06:25
Duplicate of #214

**Closed by harikesh409** 2021-03-23 06:25 UTC
Labels: bug

**Comment by alkatrivedi** [comment] 2021-03-23 06:57
I apologize for my mistake.

**Comment by harikesh409** [comment] 2021-03-24 06:57
> I apologize for my mistake.

Not a problem
