### ISSUE TITLE
Aligning the header text in the center

### ISSUE THREAD

**Issue by shubhraagarwal** [Algo-Phantoms/Algo-Phantoms-Frontend#82] opened 2021-03-10 06:24 UTC
![image](https://user-images.githubusercontent.com/67220475/110585713-2bcf9000-8197-11eb-94ca-347a156c863e.png)
The header text is currently aligned to the left while the heading is aligned to the center, I would like to align the text to the center so that it looks better.

This contirbution is under GS'SOC21

**Comment by ShrutiKhatri826** [comment] 2021-03-10 15:26
I am a GSSOC'21 participant. I would love to take on this issue. Can you please assign it to me? Hope to hear from you soon!

**Comment by Goheljay** [comment] 2021-03-10 16:25
I am a GSSOC'21 participant. but I have already complete this issue. and also have already sent a pull request. https://github.com/Algo-Phantoms/Algo-Phantoms-Frontend/pull/66

**Comment by rk05-lenavo** [comment] 2021-03-13 11:52
I'm the participant in GSSOC'21. Could you please assign me this.I would love working on this.

**Comment by amritakesh** [comment] 2021-03-15 17:54
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by agamjotsingh18** [comment] 2021-03-23 17:24
Hello , GSSoC participanr would love to take this issues , would you like to assign it to me ?

**Comment by harikesh409** [comment] 2021-03-24 06:30
The issue is already fixed.
![image](https://user-images.githubusercontent.com/3501554/112265481-91904180-8c98-11eb-8e29-e3c5bd65e1ba.png)

**Closed by harikesh409** 2021-03-24 06:30 UTC
