### ISSUE TITLE
Form for contact page

### ISSUE THREAD

**Issue by fatma-sia27** [Algo-Phantoms/Algo-Phantoms-Frontend#144] opened 2021-03-14 10:22 UTC
Hey, I had visited this Algo Phantoms website. And I think it would  be great if we add a short form type in CONTACT pae, like we can ask users name, email , their issus or suggestions, etc. I found this great, and I want to add this form to CONTACT page so please assign me this issue.
Thank you 
Aasia fatma

**Comment by abhishek96k** [comment] 2021-03-14 11:54
Hey @todi-2000 I would like to work on this issue. Please `assign` this issue to me.

**Comment by harikesh409** [comment] 2021-03-16 11:37
Duplicate of #51 #83

**Closed by harikesh409** 2021-03-16 11:37 UTC
