### ISSUE TITLE
Overlapping of icon and email input field on social-sidebar.

### ISSUE THREAD

**Issue by AyushPradhan9** [Algo-Phantoms/Algo-Phantoms-Frontend#233] opened 2021-03-23 16:58 UTC
## **Describe the bug**

Overlapping of social-sidebar is creating a unpleasant UI experience. By putting social-sidebar we can fix it. Please assign it to me being a participant of GGSOC.

## **Possible solution**

Adding z-index to social-sidebar solves the problem.

### Current website:-
![bandicam 2021-03-23 22-12-33-503](https://user-images.githubusercontent.com/52281409/112185873-a0d6a700-8c26-11eb-8477-d74d10c47cf5.jpg)

### After fix:-
![bandicam 2021-03-23 22-19-48-162](https://user-images.githubusercontent.com/52281409/112185933-adf39600-8c26-11eb-815f-cd8ecc0cfe72.jpg)

**Comment by harikesh409** [comment] 2021-03-24 06:33
Duplicate of #179

**Closed by harikesh409** 2021-03-24 06:33 UTC
Labels: bug
