### ISSUE TITLE
Add floating animation in image of about us section

### ISSUE THREAD

**Issue by Shivangi-ch** [Algo-Phantoms/Algo-Phantoms-Frontend#459] opened 2021-04-27 04:14 UTC
## **Is your feature request related to a problem? Please describe.**

-No its not related to a problem.

## **Describe the solution you'd like**

- I would like to add the floating animation in image so that the page looks more attractive .
- 
![Screenshot from 2021-04-27 09-33-06](https://user-images.githubusercontent.com/57783826/116184219-f11cb980-a73c-11eb-9f44-ab6f23b5006b.png)
Originally it look like this. Floating image will make it look more nice.
Please assign this to me.

**Comment by harikesh409** [comment] 2021-04-27 05:37
Duplicate of #456

**Closed by harikesh409** 2021-04-27 05:37 UTC
Labels: enhancement
