### ISSUE TITLE
Motion of the about us image

### ISSUE THREAD

**Issue by Spardha-hash** [Algo-Phantoms/Algo-Phantoms-Frontend#501] opened 2021-05-18 07:04 UTC
I want to make the about us image in motion somewhat like bouncing that make it more interactive. So @harikesh409 please assign this issue to me.

![Screenshot (103)](https://user-images.githubusercontent.com/65541725/118606558-33359a00-b7d5-11eb-9244-f99a2ff61e3a.png)

**Comment by harikesh409** [comment] 2021-05-18 15:09
Duplicate of #456 #459

**Closed by harikesh409** 2021-05-18 15:09 UTC
Labels: enhancement
