### ISSUE TITLE
Adding book link or a playlist

### ISSUE THREAD

**Issue by Aarti002** [Algo-Phantoms/Algo-Phantoms-Frontend#438] opened 2021-04-23 04:09 UTC
In SHARPEN YOUR SKILL section we can provide book links and a playlist links to make it easier for user to learn that particular topic.
@ravikr126 can i work on it?
Thank you!

**Comment by harikesh409** [comment] 2021-04-24 11:36
Duplicate of #427

**Closed by harikesh409** 2021-04-24 11:36 UTC
Labels: enhancement
