### ISSUE TITLE
Adjusting Spacings in the footer

### ISSUE THREAD

**Issue by anhushree** [Algo-Phantoms/Algo-Phantoms-Frontend#103] opened 2021-03-11 04:11 UTC
The spacing in the footer is not consistent under three responsive sizes (Laptop, Tablet, Mobile)
![laptop](https://user-images.githubusercontent.com/56672958/110733811-9ee70e00-824c-11eb-8dfc-b3fd6414fad7.PNG)
![tablet](https://user-images.githubusercontent.com/56672958/110733981-ee2d3e80-824c-11eb-8da9-9451edb6c050.PNG)
![mobile](https://user-images.githubusercontent.com/56672958/110733991-f1282f00-824c-11eb-8d2c-e31c2ef2355d.PNG)

**Comment by anhushree** [comment] 2021-03-11 04:12
Can I work on this issue as a GSSoC'21 Participant?

**Comment by Dimple115** [comment] 2021-03-13 09:51
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by Fpj-11** [comment] 2021-03-13 15:12
I am a gssoc'21 participant. I would like to work on this issue.

**Comment by harikesh409** [comment] 2021-03-16 05:03
The issue is quite similar to #95.

**Closed by harikesh409** 2021-03-16 05:03 UTC
