### ISSUE TITLE
Follow us button

### ISSUE THREAD

**Issue by tier3guy** [Algo-Phantoms/Algo-Phantoms-Frontend#311] opened 2021-04-01 10:52 UTC
@harikesh409 sir in the follow us button , the transition are too fast and its not looking good , can I work on that and enhance the transition effect .

please assign me this so that I can work on that.

**Comment by harikesh409** [comment] 2021-04-02 06:50
Can you post some screenshots on how you want to change it?

**Comment by Khushi-agarwal** [comment] 2021-04-03 19:02
Can I work on this issue.I will create a hover effect on the icons.
@harikesh409 @ravikr126

**Comment by harikesh409** [comment] 2021-04-05 17:55
Duplicate of #307

**Closed by harikesh409** 2021-04-05 17:55 UTC
