### ISSUE TITLE
On Hovering The Logo It get Blurred

### ISSUE THREAD

**Issue by LalitMishra1504** [Algo-Phantoms/Algo-Phantoms-Frontend#196] opened 2021-03-17 16:51 UTC
In About-Us Section On Hovering The Logo it get Blurred
I will Try to resolve this issue
can you please assign me this @harikesh409 
![Screenshot (1055)](https://user-images.githubusercontent.com/78636179/111505096-46dd6980-876e-11eb-830a-421cffeddd4e.png)

**Comment by harikesh409** [comment] 2021-03-17 16:55
Duplicate of #179

**Closed by harikesh409** 2021-03-17 16:55 UTC
Labels: duplicate
