### ISSUE TITLE
Background of About us section

### ISSUE THREAD

**Issue by RahulBansal0502** [Algo-Phantoms/Algo-Phantoms-Frontend#443] opened 2021-04-23 09:14 UTC
![image](https://user-images.githubusercontent.com/56486309/115849125-35107580-a442-11eb-8e6e-74ce1784c55e.png)
![image](https://user-images.githubusercontent.com/56486309/115849398-799c1100-a442-11eb-8d7a-d6781386869e.png)
![image](https://user-images.githubusercontent.com/56486309/115849447-828ce280-a442-11eb-8ba0-04f86e35f3e3.png)

I want to make such type of background @harikesh409 @ravikr126 please give your suggestions on this.

**Comment by harikesh409** [comment] 2021-04-24 08:12
Duplicate of #175

**Closed by harikesh409** 2021-04-24 08:12 UTC
