### ISSUE TITLE
Changes in Meet our team section

### ISSUE THREAD

**Issue by Khushi-agarwal** [Algo-Phantoms/Algo-Phantoms-Frontend#304] opened 2021-03-31 10:41 UTC
The meet our team section can be made more appealing by adding a little bit of flip card animation to it and also by adding a bright color to it.
So can I work on this issue.
Please @Shruti3004 @harikesh409 @ravikr126 assign it to me.

**Comment by harshb02** [comment] 2021-03-31 15:45
I am already working on the meet our team sections and have made some changes in the section. So if you have any more idea we can work together on the section if you want @Khushi-agarwal

**Comment by harshb02** [comment] 2021-03-31 18:25
> Yes sure @harshb02 but for that I need to be assigned this issue, then only we can work on it.

Okay no problem.

**Comment by harikesh409** [comment] 2021-03-31 18:32
@Khushi-agarwal as you are interested to work along with @harshb02 I will be assigning to the issue.

Closing this as it is a duplicate of #279

**Closed by harikesh409** 2021-03-31 18:32 UTC
Labels: enhancement
