### ISSUE TITLE
Adding smooth scrolling in the back to top button

### ISSUE THREAD

**Issue by shubhraagarwal** [Algo-Phantoms/Algo-Phantoms-Frontend#81] opened 2021-03-10 06:21 UTC
The scroll behaviour is not smooth in the back to top button, I would like to improve this as a part of GS'SOC21. Adding smooth scroll behaviour will make the UX better.

**Comment by Shruti3004** [comment] 2021-03-10 09:33
go ahead @shubhraagarwal

**Comment by shubhraagarwal** [comment] 2021-03-10 13:37
I have made a PR #96 with respect to this issue

**Comment by ishwari20** [comment] 2021-05-16 08:47
@ravikr126 I want to work on this issue. Please assign it to me

**Comment by harshb02** [comment] 2021-05-17 14:56
I want to work on this issue @ravikr126 @harikesh409

**Comment by harikesh409** [comment] 2021-05-18 15:38
The issue is already resolved in #131

**Closed by harikesh409** 2021-05-18 15:38 UTC
Labels: GSSOC21, enhancement, level2
