### ISSUE TITLE
Banner text not center-aligned in mobile-view

### ISSUE THREAD

**Issue by SilverGraph** [Algo-Phantoms/Algo-Phantoms-Frontend#462] opened 2021-05-03 03:41 UTC
## **Describe the bug**

- The banner text is not center-aligned in mobile-view

## **Possible solution**

- Aligning the banner text at center in mobile-view

## **Screenshots**

![Screenshot 2021-05-03 091025](https://user-images.githubusercontent.com/74287708/116839292-70076b80-abef-11eb-848d-58b2ad97e04d.png)

**Comment by harikesh409** [comment] 2021-05-08 10:13
Duplicate of #112

**Closed by harikesh409** 2021-05-08 10:13 UTC
Labels: bug
