### ISSUE TITLE
Email-id validation

### ISSUE THREAD

**Issue by shrishti-c** [Algo-Phantoms/Algo-Phantoms-Frontend#319] opened 2021-04-02 13:46 UTC
## **Is your feature request related to a problem? Please describe.**

- Method to validate the email-id in contact us section in order to make sure a legitimate id has been provided.

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by harikesh409** [comment] 2021-04-02 14:06
Duplicate of #115

**Closed by harikesh409** 2021-04-02 14:06 UTC
Labels: enhancement
