### ISSUE TITLE
Click issue in Features section Our Team Page 

### ISSUE THREAD

**Issue by abhishek96k** [Algo-Phantoms/Algo-Phantoms-Frontend#228] opened 2021-03-22 19:14 UTC
## **Describe the bug**
In the features section the lists are clickable even when cursor is far away.

## **Possible solution**

 I would like to work on this issue as part of GSSOC'21. Please assign me this issue.

## **Video**

https://user-images.githubusercontent.com/54280252/112045165-893ce700-8b70-11eb-9ea0-e2cd62e7f75f.mp4

**Comment by harikesh409** [comment] 2021-03-23 06:32
Duplicate of #208

**Comment by abhishek96k** [comment] 2021-03-30 09:31
> Duplicate of #208

They are not a duplicate please check again

**Comment by harikesh409** [comment] 2021-03-30 18:07
Okay the description and video are same so I marked as duplicate didn't notice that you were talking about the teams page.
Go ahead @abhishek96k

**Closed** 2021-03-31 09:14 UTC
Labels: GSSOC21, bug, level1
