### ISSUE TITLE
Alignment of sharpen your skills is not centered

### ISSUE THREAD

**Issue by saswatsam786** [Algo-Phantoms/Algo-Phantoms-Frontend#484] opened 2021-05-15 18:19 UTC
## **Describe the bug**
Sharpen your skills is not centered
- A clear and concise description of what the bug is.

## **Possible solution**
margins should be fixed
- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/77463804/118374062-bc7f7d80-b5d7-11eb-8cf1-ee424b569e9a.png)
![Capture](https://user-images.githubusercontent.com/77463804/118374091-e2a51d80-b5d7-11eb-82d4-f38f04c26da9.PNG)

- If applicable, add screenshots to help explain your problem.
I have added the screenshot after and before...if it's an issue that can be fixed then please assign it to me. I am GSSOC'21 participant @harikesh409

**Comment by harikesh409** [comment] 2021-05-16 08:13
Duplicate of #426 #391

**Closed by harikesh409** 2021-05-16 08:13 UTC
Labels: bug
