### ISSUE TITLE
Cascading styles of Contact Us button #gssoc21

### ISSUE THREAD

**Issue by Srijan205** [Algo-Phantoms/Algo-Phantoms-Frontend#152] opened 2021-03-15 10:16 UTC
I would like to change the CSS styles used in the Contact Us button, by adding the toggle feature when it is being hovered.
@gssoc21

**Comment by harikesh409** [comment] 2021-03-16 11:31
Duplicate of #63

**Closed by harikesh409** 2021-03-16 11:31 UTC
