### ISSUE TITLE
Gssoc'21 Bug in Home Page

### ISSUE THREAD

**Issue by arpit456jain** [Algo-Phantoms/Algo-Phantoms-Frontend#240] opened 2021-03-24 10:35 UTC
## **Describe the bug**
There is a bug in the code because of which in phone view the about us heading is collapsing with social-sidebar.
I am attaching a video for better understanding of my issue.

https://user-images.githubusercontent.com/55352601/112296157-a4b40900-8cba-11eb-87b4-79b082f7adbe.mp4

## **Possible solution**
I have to check the code If it assign to me

**Comment by harikesh409** [comment] 2021-03-24 10:39
Duplicate of #179

**Closed by harikesh409** 2021-03-24 10:39 UTC
Labels: bug
