### ISSUE TITLE
JavaScript Error in team.html

### ISSUE THREAD

**Issue by tanishq-arya** [Algo-Phantoms/Algo-Phantoms-Frontend#419] opened 2021-04-17 12:36 UTC
## **Describe the bug**

- There is an error in scroll functionality in team.html
- Check by inspecting the team element console. { Shift + Ctrl + i }

**Comment by tanishq-arya** [comment] 2021-04-17 12:37
Please assign me this issue under gssoc

**Comment by harikesh409** [comment] 2021-04-24 15:41
Duplicate of #397

**Closed by harikesh409** 2021-04-24 15:41 UTC
Labels: bug
