### ISSUE TITLE
Validating the email in the team page

### ISSUE THREAD

**Issue by 123mansha** [Algo-Phantoms/Algo-Phantoms-Frontend#219] opened 2021-03-20 18:16 UTC
In the team's contact us page the email field is not validating whether we entered a plaintext or an email i.e., A valid email must contain '@' symbol.
Here, in the below screenshot we can see that no error message is displayed even if we are entering a plain text in the email field.

![algofr](https://user-images.githubusercontent.com/59260493/111881390-3f1ffe00-89d6-11eb-99e6-2c42a2760448.jpg)

I would like to work on this issue.

**Comment by 123mansha** [comment] 2021-03-20 18:20
@Shruti3004 kindly assign me this issue

**Comment by harikesh409** [comment] 2021-03-22 08:19
Duplicate of #115

**Closed by harikesh409** 2021-03-22 08:19 UTC
Labels: Gssoc21, bug
