### ISSUE TITLE
Revamp Team page

### ISSUE THREAD

**Issue by RahulBansal0502** [Algo-Phantoms/Algo-Phantoms-Frontend#250] opened 2021-03-25 12:29 UTC
@ravikr126 @harikesh409 I wanted to merge the teams' page section with the home page like the About us section. As it's looking weird if all the sections open up on the same page and the teams page opens up separately. Please assign this issue to me as a GSSOC participant.

**Comment by harikesh409** [comment] 2021-03-29 04:31
Duplicate of #69

**Closed by harikesh409** 2021-03-29 04:31 UTC
