### ISSUE TITLE
Style the button on "Roadmap to your DSA" page

### ISSUE THREAD

**Issue by ishwari20** [Algo-Phantoms/Algo-Phantoms-Frontend#292] opened 2021-03-30 09:24 UTC
## **Is your feature request related to a problem? Please describe.**

- The current button is very simple and doesn't go with the theme of the website

## **Describe the solution you'd like**

- Style the button according to the theme of the website

**Comment by ishwari20** [comment] 2021-03-30 09:25
@Shruti3004 Please assign this issue to me. I want to work on it.

**Comment by harikesh409** [comment] 2021-03-30 18:20
Duplicate of #185 #206

**Closed by harikesh409** 2021-03-30 18:20 UTC
Labels: enhancement
