### ISSUE TITLE
Improving the contact us form

### ISSUE THREAD

**Issue by shubhraagarwal** [Algo-Phantoms/Algo-Phantoms-Frontend#83] opened 2021-03-10 06:31 UTC
The contact us form is only having the email section, this might be inconvinient as the Algo phantoms team won't know why the user wants to contact them and sending mails back and forth will be time consuming, so I am proposing to include other sections in the form too like Name, email, contact number and a message section. It will look something like this in the end.
![image](https://user-images.githubusercontent.com/67220475/110586466-4d7d4700-8198-11eb-82d5-497131fc13ce.png)

I would like to work on this under GS'SOC21

**Comment by samrat1223** [comment] 2021-03-10 11:01
Can I work on this issue ?

**Comment by HarinandhanPSGiTech** [comment] 2021-03-10 12:17
I am a GSSOC'21 participant, I would love to contribute to this issue, and I will deliver my best output

**Comment by ShrutiKhatri826** [comment] 2021-03-10 15:25
I am a GSSOC'21 participant. I would love to take on this issue. Can you please assign it to me? Hope to hear from you soon!

**Comment by ambivert-sam** [comment] 2021-03-10 17:19
Hey!!
@shubhraagarwal I am participate at GSSoC'21 I would like to work with this issue
Would you please assign it to me?
I'll put my best in it.

**Comment by ravikr126** [comment] 2021-03-13 12:39
sure @shubhraagarwal you can start now and add some hover effect on the button also

**Comment by shubhraagarwal** [comment] 2021-03-15 07:59
@ravikr126 Please review my earlier PR #96 so that I can create a new PR with the form

**Comment by amritakesh** [comment] 2021-03-15 17:53
hello
i'm taking part in gssoc 2021. And i would like work on this creating a form, will you please assign this to me?

**Comment by harikesh409** [comment] 2021-03-16 11:38
Duplicate of #51

**Closed by harikesh409** 2021-03-16 11:38 UTC
