### ISSUE TITLE
social-sidebar background color

### ISSUE THREAD

**Issue by lipsa199** [Algo-Phantoms/Algo-Phantoms-Frontend#203] opened 2021-03-18 07:04 UTC
Description of issue:
** when the webpage minimizes or open in phone size browser the social sidebar is not properly visible on footer part because of the   background color of social sidebar**
![IMG_20210318_123048](https://user-images.githubusercontent.com/76063097/111585850-ef7ae000-87e5-11eb-863d-2c41b5da795d.jpg)

**Comment by lipsa199** [comment] 2021-03-20 17:56
@Shruti3004  can I work on this issue as a participant of gssoc21?

**Comment by lipsa199** [comment] 2021-03-21 08:25
@harikesh409 can i work on this as a participant of gssoc21?

**Comment by kumar-tushar** [comment] 2021-03-22 17:58
@Shruti3004  
I have added an issue regarding the change of FOOTER CONTENT in CENTER (issue #226).
This will solve all problems.
So, I Can I work on this issue as a GSSOC 21 participant?

**Comment by harikesh409** [comment] 2021-03-23 06:23
The issue is similar to #179 if it is not resolved in that then you can work on it.

**Comment by lipsa199** [comment] 2021-03-23 15:26
@harikesh409 ok sir

**Comment by kumar-tushar** [comment] 2021-03-29 18:17
> The issue is similar to #179 if it is not resolved in that then you can work on it.

@harikesh409 The issue is still not resolved for mobile devices.
I want to make the text content of the footer in the center to solve the problem of overlapping.
Can I go ahead?

**Comment by harikesh409** [comment] 2021-03-30 18:38
> > The issue is similar to #179 if it is not resolved in that then you can work on it.
> 
> @harikesh409 The issue is still not resolved for mobile devices.
> I want to make the text content of the footer in the center to solve the problem of overlapping.
> Can I go ahead?

Already a PR #185 is present for it.

**Comment by harikesh409** [comment] 2021-04-24 16:55
The social media sidebar has been removed in phone views in #435

**Closed by harikesh409** 2021-04-24 16:55 UTC
Labels: GSSOC21, bug, level2
