### ISSUE TITLE
Animation is not working for some cards in the Team page.

### ISSUE THREAD

**Issue by shonali2600** [Algo-Phantoms/Algo-Phantoms-Frontend#317] opened 2021-04-02 06:58 UTC
## **Describe the bug**
In the team page, some cards tilt on hovering, while some don't.

## **Possible solution**
I'll rectify this problem.

## **Screenshots**

https://user-images.githubusercontent.com/57946528/113389830-4f5cb380-93ae-11eb-82e0-55e6d2de15d0.mp4

**Comment by harikesh409** [comment] 2021-04-02 07:50
Duplicate of #277

**Closed by harikesh409** 2021-04-02 07:50 UTC
Labels: bug
