### ISSUE TITLE
[Need] Issue and PR template 

### ISSUE THREAD

**Issue by Aryamanz29** [Algo-Phantoms/Algo-Phantoms-Frontend#153] opened 2021-03-15 10:30 UTC
Currently, we haven't any issue and PR template for this repo

**Comment by Aryamanz29** [comment] 2021-03-15 10:30
I would like to contribute to this issue

**Comment by harikesh409** [comment] 2021-03-16 11:23
Duplicate of #53

**Closed by harikesh409** 2021-03-16 11:23 UTC
