### ISSUE TITLE
FOOTER CONTENT must be in center for mobile view . Also overlapping FOOTER problem will be solved

### ISSUE THREAD

**Issue by kumar-tushar** [Algo-Phantoms/Algo-Phantoms-Frontend#226] opened 2021-03-22 17:50 UTC
![Screenshot_2021-03-22-23-04-07-737_com android chrome](https://user-images.githubusercontent.com/56949668/112034918-06faf580-8b65-11eb-906f-10d7865b7c96.jpg)

**Comment by harikesh409** [comment] 2021-03-23 06:21
Duplicate of #179

**Closed by harikesh409** 2021-03-23 06:21 UTC
Labels: enhancement
