### ISSUE TITLE
Improve alignment of navbar in responsive and normal view

### ISSUE THREAD

**Issue by AyushPradhan9** [Algo-Phantoms/Algo-Phantoms-Frontend#255] opened 2021-03-26 03:20 UTC
## Proposal
I would like to improve the alignment of whole navbar by improving it with bootstrap and making it more symmetrical and aesthetic while in dropdown or in large screens.

## Screenshots
Notice that left side is much to the left and right side is almost in the center making it asymmetrical.
![bandicam 2021-03-26 08-43-14-513](https://user-images.githubusercontent.com/52281409/112572374-118ce780-8e10-11eb-9ebf-22598d4959d0.jpg)
The dropdown menu is to the right altogether making it asymmetrical.
![bandicam 2021-03-26 08-44-05-768](https://user-images.githubusercontent.com/52281409/112572377-12be1480-8e10-11eb-9f18-748a97ef4ef2.jpg)

**Comment by harikesh409** [comment] 2021-03-27 08:39
Duplicate of #251

**Closed by harikesh409** 2021-03-27 08:39 UTC
