### ISSUE TITLE
Adding Parallax scrolling effect 

### ISSUE THREAD

**Issue by shrishti-c** [Algo-Phantoms/Algo-Phantoms-Frontend#106] opened 2021-03-11 05:20 UTC
To enhance the home page of Algo Phantom, we can use parallax scrolling effect. Please assign me this issue.

**Comment by simranbhalla3** [comment] 2021-03-11 09:22
I can add parallax scrolling effect in the website. Project mentor @Shruti3004 please assign this issue to me

**Comment by harikesh409** [comment] 2021-03-27 08:41
Duplicate of #71

**Closed by harikesh409** 2021-03-27 08:41 UTC
